<a href="https://colab.research.google.com/github/BrunaFerreira/Mestrado_UNIFESP/blob/main/Revisao_4_GrandesNumeros.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Grandes Números, Tabelas e Graficos**

In [ ]:
!pip install -q gspread gspread-dataframe

In [ ]:
import pandas as pd
import numpy as np
import re
#from google.colab import drive
#drive.mount('/content/drive')

In [ ]:
path = '/content/drive/MyDrive/0_Mestrado_unifesp/3_Pesquisa/Revisao/202607_Revisao_Completa'

### **Grandes Números**

#### **Filtro 1: Seleção de artigos selecionados**

In [ ]:
df_filtro1 = pd.read_csv(path + '/1_Artigos_Filtrados/1_Lista_Completa_Artigos_20260710.csv')
df_filtro1.loc[df_filtro1["Base"] == "Pubmed", "Base"] = "PubMed"
print('Quantidade de artigos apos filtro de queries:', df_filtro1.shape[0])

Quantidade de artigos apos filtro de queries: 680

In [ ]:
df_filtro1.Base.value_counts()

Base
Scopus    586
PubMed     94
Name: count, dtype: int64

#### **Filtro 2: Remoção de Artigos duplicados**

In [ ]:
df_filtro2 = df_filtro1[df_filtro1['Repetidos']==0]
print('Quantidade de artigos duplicados:', df_filtro1.shape[0] - df_filtro2.shape[0])
print('Quantidade de artigos restantes:',  df_filtro2.shape[0])

Quantidade de artigos duplicados: 219
Quantidade de artigos restantes: 461

#### **Filtro 3: Critérios de Exclusão**



```
# 1. Artigos de Conferência
```

In [ ]:
df_filtro3 = df_filtro2[df_filtro2['Criterios']!='Conference Review']
print('Quantidade de artigos como "Conference Review":', df_filtro2.shape[0] - df_filtro3.shape[0])
print('Quantidade de artigos restantes:',  df_filtro3.shape[0])

Quantidade de artigos como "Conference Review": 33
Quantidade de artigos restantes: 428



```
# 2. Artigos sem acesso ao texto completo
```

In [ ]:
#from google.colab import auth
#auth.authenticate_user()
#
#import gspread
#from google.auth import default
#from gspread_dataframe import get_as_dataframe
#
#creds, _ = default()
#gc = gspread.authorize(creds)

In [ ]:
#sh = gc.open("VF_Perguntas_Respostas")
#
#worksheet = sh.get_worksheet(1)   # primeira aba
## worksheet = sh.get_worksheet(1) # segunda aba
#
#df_filtro4 = get_as_dataframe(
#    worksheet,
#    evaluate_formulas=True
#)

In [ ]:
#exclusao = df_filtro4[df_filtro4['Status']=='Nao da pra baixar arquivo']
##conferencia  = df_filtro3[df_filtro3['Criterio_Final']=='Conference Review']
##print('Quantidade de artigos de Conferencia :', conferencia.shape[0])
#print('Quantidade de artigos sem acesso para baixar :', exclusao.shape[0])
#
#qtd_final = df_filtro2.shape[0] - conferencia.shape[0] - exclusao.shape[0]
#print('Quantidade de artigos apos avaliar criterios de exclusão :', qtd_final)

Foram encontrados 8 artigos sem acesso completo sendo:

*   5 artigos ate maio de 2026
*   3 artigos em junho de 2026

In [ ]:
print('Quantidade de artigos restantes:',  df_filtro3.shape[0]-8)

Quantidade de artigos restantes: 420

#### **Filtro 4: Seleção por Abstract**

In [ ]:
df_filtro4 = pd.read_csv(path + '/2_Perguntas_Pesquisa/3_Lista_Final_Artigos_Revisao_202607.csv')

In [ ]:
print('Quantidade de artigos com abstract não aderente:',  df_filtro3.shape[0]-8-df_filtro4.shape[0])
print('Quantidade de artigos com abstract aderente:',  df_filtro4.shape[0])

Quantidade de artigos com abstract não aderente: 259
Quantidade de artigos com abstract aderente: 161

### **Relação de Artigos aderentes e descartados**

In [ ]:
print(df_filtro1['Query'].value_counts().sort_index())

Query
6.0      57
7.0       6
9.0     250
11.0    252
12.0      8
13.0    107
Name: count, dtype: int64

In [ ]:
print(df_filtro4['Query_A'].value_counts().sort_index())

Query_A
6.0     18
7.0      2
9.0     53
11.0    88
Name: count, dtype: int64

### **Relação de Artigos de Revisão**

In [ ]:
Q6 = df_filtro4[['DOI', 'Query_A', 'Base', 'Nome_A', 'Questao_18']]

In [ ]:
Q6['Questao_18'].value_counts()

Questao_18
Não                                                                                                                                                                                                                                                                                                                                                                                                                                                             130
Sim                                                                                                                                                                                                                                                                                                                                                                                                                                                              26
Não                                                                                                                                                                                                                                                                                                                                                                                                                                                               1
1️⃣ Bases de Dados de Imagens Médicas 🏥\nChestXray14 – 112.120 radiografias de tórax com 14 categorias de doenças.\nCheXpert – 224.316 radiografias com anotações clínicas.\nMIMIC-CXR – Radiografias extraídas de registros médicos do Beth Israel Deaconess Medical Center.\n2️⃣ Bases de Dados de Imagens Naturais 🌍\nImageNet-1K – Usada para aprendizado auto-supervisionado.\nImageNet-21K – Contém milhões de imagens para modelos supervisionados.\n      1
Name: count, dtype: int64

In [ ]:
print('Quantidade de artigos de revisão:',  df_filtro4[df_filtro4['Questao_18']=='Sim'].shape[0])

Quantidade de artigos de revisão: 26